# GitLab Test Configuration
# Simplified configuration for GitLab upgrade testing

gitlab:
  namespace: "testing-gitlab-upgrade"
  name: "upgrade-test-gitlab"
  values_file: "testdata/gitlab-template.yaml"
  gitlab_root_password: "07Apples@"
  timeout: 300

# Import project configuration
# Only one project will be imported for testing repository data preparation
import_project:
  file_path: "testdata/repo/test-upgrade-repo_export.tar.gz"
  project_name: "test-upgrade-repo"

# Version group configuration
# The top-level group that contains all test data
version_group:
  name: "upgrade-test-data"
  path: "upgrade-test-data"

# Generation rules for sub-groups and projects
# Define how many sub-groups to create and how many projects per sub-group
generation_rules:
  sub_groups_count: 3
  projects_per_sub_group: 3
  sub_group_prefix: "group"
  project_prefix: "project" 
