operatorConfig:
  workspace: /Users/mac/Desktop/kychen/alaudadevops/gitlab-operator/testing
  namespace: gitlab-ce-operator
  name: gitlab-ce-operator
upgradePaths: # 定义升级路径，可以包含多个
   - name: v17.8 upgrade to v17.11 # 升级名称
     versions: # 定义升级路经
       - name: v17.8 # 版本名称
         testCommand: |
          export REPORT=allure
          TAGS=@prepare-17.8 make test
         bundleVersion: v17.8.10
         channel: stable
       - name: v17.11 # 版本名称
         testCommand: |
          TAGS=@upgrade-17.11 GODOG_ARGS="--godog.format=allure --bdd.cleanup=false" make test
         bundleVersion: v17.11.1
         channel: stable

